SeaQuest Offline Software: SHit_v1 Class Reference
SHit_v1 Class Reference
#include <fun4all/interfaces/SHit_v1.h>
Public Member Functions
SHit_v1 ()
virtual ~SHit_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SHit * Clone () const
virtual int get_hit_id () const
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
virtual void set_detector_id (const short a)
virtual short get_element_id () const
virtual void set_element_id (const short id)
virtual float get_tdc_time () const
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
virtual void set_drift_distance (const float a)
virtual float get_pos () const
virtual void set_pos (const float a)
virtual bool is_in_time () const
virtual void set_in_time (const bool a)
virtual bool is_hodo_mask () const
virtual void set_hodo_mask (const bool a)
virtual bool is_trigger_mask () const
virtual void set_trigger_mask (const bool a)
Public Member Functions inherited from SHit
virtual ~SHit ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Member Functions
ClassDef (SHit_v1, 1)
Private Attributes
int _hit_id
short _detector_id
short _element_id
float _tdc_time
float _drift_distance
float _pos
unsigned short _flag
Additional Inherited Members
Public Types inherited from SHit
enum HitQuality { InTime = 1<<0, HodoMask = 1<<1, TriggerMask = 1<<2 }
Protected Member Functions inherited from SHit
SHit ()
Detailed Description
Definition at line 17 of file SHit_v1.h.
Constructor & Destructor Documentation
SHit_v1::SHit_v1 ()
Definition at line 18 of file SHit_v1.C.
Referenced by Clone(), and Reset().
virtual SHit_v1::~SHit_v1 () inline virtual
Definition at line 22 of file SHit_v1.h.
Member Function Documentation
SHit_v1::ClassDef (SHit_v1 , 1) private
SHit* SHit_v1::Clone () const inline virtual
Reimplemented from SHit.
Definition at line 29 of file SHit_v1.h.
References SHit_v1().
virtual short SHit_v1::get_detector_id () const inline virtual
Reimplemented from SHit.
Definition at line 36 of file SHit_v1.h.
References _detector_id.
Referenced by identify().
virtual float SHit_v1::get_drift_distance () const inline virtual
Reimplemented from SHit.
Definition at line 45 of file SHit_v1.h.
References _drift_distance.
Referenced by identify().
virtual short SHit_v1::get_element_id () const inline virtual
Reimplemented from SHit.
Definition at line 39 of file SHit_v1.h.
References _element_id.
Referenced by identify().
virtual int SHit_v1::get_hit_id () const inline virtual
Reimplemented from SHit.
Definition at line 33 of file SHit_v1.h.
References _hit_id.
Referenced by identify().
virtual float SHit_v1::get_pos () const inline virtual
Reimplemented from SHit.
Definition at line 48 of file SHit_v1.h.
References _pos.
Referenced by identify().
virtual float SHit_v1::get_tdc_time () const inline virtual
Reimplemented from SHit.
Definition at line 42 of file SHit_v1.h.
References _tdc_time.
Referenced by identify().
void SHit_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SHit.
Definition at line 28 of file SHit_v1.C.
References get_detector_id(), get_drift_distance(), get_element_id(), get_hit_id(), get_pos(), get_tdc_time(), is_hodo_mask(), is_in_time(), and is_trigger_mask().
virtual bool SHit_v1::is_hodo_mask () const inline virtual
Implements SHit.
Definition at line 54 of file SHit_v1.h.
References _flag, and SHit::HodoMask.
Referenced by identify().
virtual bool SHit_v1::is_in_time () const inline virtual
Implements SHit.
Definition at line 51 of file SHit_v1.h.
References _flag, and SHit::InTime.
Referenced by identify().
virtual bool SHit_v1::is_trigger_mask () const inline virtual
Implements SHit.
Definition at line 57 of file SHit_v1.h.
References _flag, and SHit::TriggerMask.
Referenced by identify().
int SHit_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SHit.
Definition at line 47 of file SHit_v1.C.
References _detector_id, _drift_distance, _element_id, _hit_id, _pos, and _tdc_time.
void SHit_v1::Reset () inline virtual
Clear Event.
Reimplemented from SHit.
Definition at line 27 of file SHit_v1.h.
References SHit_v1().
virtual void SHit_v1::set_detector_id (const short a) inline virtual
Reimplemented from SHit.
Definition at line 37 of file SHit_v1.h.
References _detector_id.
virtual void SHit_v1::set_drift_distance (const float a) inline virtual
Reimplemented from SHit.
Definition at line 46 of file SHit_v1.h.
References _drift_distance.
virtual void SHit_v1::set_element_id (const short id) inline virtual
Reimplemented from SHit.
Definition at line 40 of file SHit_v1.h.
References _element_id.
virtual void SHit_v1::set_hit_id (const int a) inline virtual
Reimplemented from SHit.
Definition at line 34 of file SHit_v1.h.
References _hit_id.
virtual void SHit_v1::set_hodo_mask (const bool a) inline virtual
Implements SHit.
Definition at line 55 of file SHit_v1.h.
References _flag, and SHit::HodoMask.
virtual void SHit_v1::set_in_time (const bool a) inline virtual
Implements SHit.
Definition at line 52 of file SHit_v1.h.
References _flag, and SHit::InTime.
virtual void SHit_v1::set_pos (const float a) inline virtual
Reimplemented from SHit.
Definition at line 49 of file SHit_v1.h.
References _pos.
virtual void SHit_v1::set_tdc_time (const float a) inline virtual
Reimplemented from SHit.
Definition at line 43 of file SHit_v1.h.
References _tdc_time.
virtual void SHit_v1::set_trigger_mask (const bool a) inline virtual
Implements SHit.
Definition at line 58 of file SHit_v1.h.
References _flag, and SHit::TriggerMask.
Member Data Documentation
short SHit_v1::_detector_id private
Definition at line 63 of file SHit_v1.h.
Referenced by get_detector_id(), isValid(), and set_detector_id().
float SHit_v1::_drift_distance private
Definition at line 67 of file SHit_v1.h.
Referenced by get_drift_distance(), isValid(), and set_drift_distance().
short SHit_v1::_element_id private
Definition at line 64 of file SHit_v1.h.
Referenced by get_element_id(), isValid(), and set_element_id().
unsigned short SHit_v1::_flag private
Definition at line 70 of file SHit_v1.h.
Referenced by is_hodo_mask(), is_in_time(), is_trigger_mask(), set_hodo_mask(), set_in_time(), and set_trigger_mask().
int SHit_v1::_hit_id private
Definition at line 62 of file SHit_v1.h.
Referenced by get_hit_id(), isValid(), and set_hit_id().
float SHit_v1::_pos private
Definition at line 68 of file SHit_v1.h.
Referenced by get_pos(), isValid(), and set_pos().
float SHit_v1::_tdc_time private
Definition at line 66 of file SHit_v1.h.
Referenced by get_tdc_time(), isValid(), and set_tdc_time().
The documentation for this class was generated from the following files:
fun4all/interfaces/SHit_v1.h
fun4all/interfaces/SHit_v1.C