#ifndef __JPSI_NRQCD_GEN_H__
#define __JPSI_NRQCD_GEN_H__

#include <string>
#include <gsl/gsl_rng.h>
#include <TGraph.h>
#include <TGenPhaseSpace.h>
#include <g4main/PHG4ParticleGeneratorBase.h>

class PHCompositeNode;
class PHG4ParticleGeneratorBase;
class PHG4InEvent;
class PHG4Particle;

class PHGenIntegral;
class SQEvent;
class SQMCEvent;
class SQDimuon;
class SQDimuonVector;
class SQPrimaryVertexGen;

//==========
/// Physics generator imported from E906 software
/**
 * Each event generated by this generator is given its own weight.
 * The event weight is defined as "cross_section(xF, mass) * beam_luminosity(x, y)".
 * You have to count up events with the event weight multiplied, namely
 * fill events to a histogram using the event weight as the weight of added contents.
 *
 * This generator creates a data node of `PHGenIntegral` under the `RUN` node.
 * The node stores the integrated luminosity etc.
 * You can divide the weighted event count by the integrated luminosity to obtain the cross section (per bin).
 * You can then multiply this cross section by an expected integrated luminosity (of spill, week, year, etc.) to obtain the expected count.
 * 
 * The generated process is accessible in analysis via SQMCEvent::get_process_id().
 * The convention of IDs (or codes) is specific to this class, as defined as `ProcessCode_t`;
 * @code
 * if (mcevt->get_process_id() == JpsiNRQCDGen::DrellYan) {...}
 * @endcode
 */
class JpsiNRQCDGen: public PHG4ParticleGeneratorBase
{
public:
  typedef enum { PROTON, DEUTERON, NITROGEN } Target_t;
  typedef enum { CTEQ, NNPDF } PDF_t;
  typedef enum { SMRS_REF, SMRS_FIT, GRV_REF, GRV_FIT, JAM_REF, JAM_FIT, xFitter_REF, xFitter_FIT } LDME_t;
  
  JpsiNRQCDGen(const std::string& name = "JpsiNRQCDGen");
  virtual ~JpsiNRQCDGen();
    
  int Init(PHCompositeNode* topNode);
  int InitRun(PHCompositeNode* topNode);
  int End(PHCompositeNode* topNode);
  int process_event(PHCompositeNode* topNode);
  
  int generateJPsi(const TVector3& vtx, const double pARatio, double luminosity);
  bool generateDimuon(double mass, double xF);

  void set_pT0JPsi  (const double val) { _pT0JPsi   = val; }
  void set_pTpowJPsi(const double val) { _pTpowJPsi = val; }

  void set_xfRange(const double xmin, const double xmax){
    xfMin = xmin;
    xfMax = xmax;
  }

  double CrossSectionJPsi(const double xF);
  
  void SetTarget(const Target_t tgt) { _tgt = tgt; }
  void SetPDF(const PDF_t pdf) { _pdf = pdf; }
  void SetLDME(const LDME_t ldme) { _ldme = ldme; }
  void SetDataDir(const std::string dir) { _dir_data = dir; }
  
 private:
  std::string _dir_data;
  Target_t _tgt;
  PDF_t _pdf;
  LDME_t _ldme;

  TGraph _gr_xsec_total;
  TGraph _gr_xsec_qqbar;
  TGraph _gr_xsec_gg;
  TGraph _gr_xsec_qg;
  
  SQPrimaryVertexGen* _vertexGen;
  PHG4InEvent* _ineve;
  SQEvent* _evt; //< An output node
  SQMCEvent* _mcevt; //< An output node
  SQDimuonVector* _vec_dim; //< An output node
  PHGenIntegral *_integral_node; //< An output node
  
  SQDimuon* _dim_gen; //< To hold the kinematics of a dimuon generated
  
  //!ROOT phase space generator
  TGenPhaseSpace phaseGen;
  
  // Parameters (being moved from DPGEN)
  double _pT0JPsi;
  double _pTpowJPsi;
  
  //some initializations
  double x1Min = 0.;
  double x1Max = 1.;
  double x2Min = 0.;
  double x2Max = 1.;
  double xfMin = -0.95;
  double xfMax =  0.95;
  double cosThetaMin = -1.;
  double cosThetaMax =  1.;
  double zOffsetMin  = -1.;
  double zOffsetMax  =  1.;
  
  void InsertMuonPair(const TVector3& vtx);
  void InsertEventInfo(const double xsec, const double weight, const TVector3& vtx);
  
  double _n_gen_acc_evt; //< N of generator-accepted events
  double _n_proc_evt; //< N of processed events
  double _weight_sum; //< Sum of weights
  double _inte_lumi; //< Integrated luminosity
};

#endif // __JPSI_NRQCD_GEN_H__
