SeaQuest Offline Software: boost Namespace Reference
boost Namespace Reference
Namespaces
detail
Classes
class array
class array< T, 0 >
class shared_ptr
class weak_ptr
class enable_shared_from_this
class enable_shared_from_this2
struct hash
Functions
template<class T , std::size_t N>
bool operator== (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator< (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator!= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator> (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator<= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator>= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
void swap (array< T, N > &x, array< T, N > &y)
template<typename T , std::size_t N>
T(& get_c_array (boost::array< T, N > &arg))[N]
template<typename T , std::size_t N>
const T(& get_c_array (const boost::array< T, N > &arg))[N]
template<class T , class U >
bool operator== (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T , class U >
bool operator!= (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T , class U >
bool operator< (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T >
void swap (shared_ptr< T > &a, shared_ptr< T > &b)
template<class T , class U >
shared_ptr< T > static_pointer_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > const_pointer_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > dynamic_pointer_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > shared_static_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > shared_dynamic_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > shared_polymorphic_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > shared_polymorphic_downcast (shared_ptr< U > const &r)
template<class T >
T * get_pointer (shared_ptr< T > const &p)
template<class E , class T , class Y >
std::basic_ostream< E, T > & operator<< (std::basic_ostream< E, T > &os, shared_ptr< Y > const &p)
template<class D , class T >
D * get_deleter (shared_ptr< T > const &p)
template<class T >
bool atomic_is_lock_free (shared_ptr< T > const *)
template<class T >
shared_ptr< T > atomic_load (shared_ptr< T > const *p)
template<class T >
shared_ptr< T > atomic_load_explicit (shared_ptr< T > const *p, memory_order)
template<class T >
void atomic_store (shared_ptr< T > *p, shared_ptr< T > r)
template<class T >
void atomic_store_explicit (shared_ptr< T > *p, shared_ptr< T > r, memory_order)
template<class T >
shared_ptr< T > atomic_exchange (shared_ptr< T > *p, shared_ptr< T > r)
template<class T >
shared_ptr< T > atomic_exchange_explicit (shared_ptr< T > *p, shared_ptr< T > r, memory_order)
template<class T >
bool atomic_compare_exchange (shared_ptr< T > *p, shared_ptr< T > *v, shared_ptr< T > w)
template<class T >
bool atomic_compare_exchange_explicit (shared_ptr< T > *p, shared_ptr< T > *v, shared_ptr< T > w, memory_order, memory_order)
template<class T >
std::size_t hash_value (boost::shared_ptr< T > const &p)
Function Documentation
template<class T > bool boost::atomic_compare_exchange (shared_ptr< T > * p, shared_ptr< T > * v, shared_ptr< T > w)
Definition at line 657 of file shared_ptr.hpp.
References boost::shared_ptr< T >::_internal_equiv(), and boost::shared_ptr< T >::swap().
Referenced by atomic_compare_exchange_explicit().
template<class T > bool boost::atomic_compare_exchange_explicit (shared_ptr< T > * p, shared_ptr< T > * v, shared_ptr< T > w, memory_order , memory_order) inline
Definition at line 682 of file shared_ptr.hpp.
References atomic_compare_exchange().
template<class T > shared_ptr<T> boost::atomic_exchange (shared_ptr< T > * p, shared_ptr< T > r)
Definition at line 641 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
Referenced by atomic_exchange_explicit().
template<class T > shared_ptr<T> boost::atomic_exchange_explicit (shared_ptr< T > * p, shared_ptr< T > r, memory_order)
Definition at line 652 of file shared_ptr.hpp.
References atomic_exchange().
template<class T > bool boost::atomic_is_lock_free (shared_ptr< T > const *) inline
Definition at line 614 of file shared_ptr.hpp.
template<class T > shared_ptr<T> boost::atomic_load (shared_ptr< T > const * p)
Definition at line 619 of file shared_ptr.hpp.
Referenced by atomic_load_explicit().
template<class T > shared_ptr<T> boost::atomic_load_explicit (shared_ptr< T > const * p, memory_order) inline
Definition at line 625 of file shared_ptr.hpp.
References atomic_load().
template<class T > void boost::atomic_store (shared_ptr< T > * p, shared_ptr< T > r)
Definition at line 630 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
Referenced by atomic_store_explicit().
template<class T > void boost::atomic_store_explicit (shared_ptr< T > * p, shared_ptr< T > r, memory_order) inline
Definition at line 636 of file shared_ptr.hpp.
References atomic_store().
template<class T , class U > shared_ptr<T> boost::const_pointer_cast (shared_ptr< U > const & r)
Definition at line 511 of file shared_ptr.hpp.
template<class T , class U > shared_ptr<T> boost::dynamic_pointer_cast (shared_ptr< U > const & r)
Definition at line 516 of file shared_ptr.hpp.
template<typename T , std::size_t N> T(& boost::get_c_array (boost::array< T, N > & arg))[N]
Definition at line 399 of file array.hpp.
template<typename T , std::size_t N> const T(& boost::get_c_array (const boost::array< T, N > & arg))[N]
Definition at line 406 of file array.hpp.
template<class D , class T > D* boost::get_deleter (shared_ptr< T > const & p)
Definition at line 603 of file shared_ptr.hpp.
References boost::shared_ptr< T >::_internal_get_deleter().
template<class T > T* boost::get_pointer (shared_ptr< T > const & p) inline
Definition at line 546 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get().
template<class T > std::size_t boost::hash_value (boost::shared_ptr< T > const & p)
Definition at line 693 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get().
template<class T , std::size_t N> bool boost::operator!= (const array< T, N > & x, const array< T, N > & y)
Definition at line 348 of file array.hpp.
template<class T , class U > bool boost::operator!= (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
Definition at line 480 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get().
template<class T , std::size_t N> bool boost::operator< (const array< T, N > & x, const array< T, N > & y)
Definition at line 344 of file array.hpp.
template<class T , class U > bool boost::operator< (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
Definition at line 496 of file shared_ptr.hpp.
References boost::shared_ptr< T >::_internal_less().
template<class E , class T , class Y > std::basic_ostream<E, T>& boost::operator<< (std::basic_ostream< E, T > & os, shared_ptr< Y > const & p)
Definition at line 573 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get().
template<class T , std::size_t N> bool boost::operator<= (const array< T, N > & x, const array< T, N > & y)
Definition at line 356 of file array.hpp.
template<class T , std::size_t N> bool boost::operator== (const array< T, N > & x, const array< T, N > & y)
Definition at line 340 of file array.hpp.
References boost::array< T, N >::begin(), and boost::array< T, N >::end().
template<class T , class U > bool boost::operator== (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
Definition at line 475 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get().
template<class T , std::size_t N> bool boost::operator> (const array< T, N > & x, const array< T, N > & y)
Definition at line 352 of file array.hpp.
template<class T , std::size_t N> bool boost::operator>= (const array< T, N > & x, const array< T, N > & y)
Definition at line 360 of file array.hpp.
template<class T , class U > shared_ptr<T> boost::shared_dynamic_cast (shared_ptr< U > const & r)
Definition at line 528 of file shared_ptr.hpp.
template<class T , class U > shared_ptr<T> boost::shared_polymorphic_cast (shared_ptr< U > const & r)
Definition at line 533 of file shared_ptr.hpp.
template<class T , class U > shared_ptr<T> boost::shared_polymorphic_downcast (shared_ptr< U > const & r)
Definition at line 538 of file shared_ptr.hpp.
References boost::shared_ptr< T >::get(), and shared_static_cast().
template<class T , class U > shared_ptr<T> boost::shared_static_cast (shared_ptr< U > const & r)
Definition at line 523 of file shared_ptr.hpp.
Referenced by shared_polymorphic_downcast().
template<class T , class U > shared_ptr<T> boost::static_pointer_cast (shared_ptr< U > const & r)
Definition at line 506 of file shared_ptr.hpp.
template<class T , std::size_t N> void boost::swap (array< T, N > & x, array< T, N > & y) inline
Definition at line 366 of file array.hpp.
References boost::array< T, N >::swap().
Referenced by boost::array< T, N >::swap().
template<class T > void boost::swap (shared_ptr< T > & a, shared_ptr< T > & b) inline
Definition at line 501 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
Referenced by boost::shared_ptr< PHTimer >::swap().