SeaQuest Offline Software: SHit Class Reference
SHit Class Reference abstract
#include <fun4all/interfaces/SHit.h>
Public Types
enum HitQuality { InTime = 1<<0, HodoMask = 1<<1, TriggerMask = 1<<2 }
Public Member Functions
virtual ~SHit ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SHit * Clone () const
virtual int get_hit_id () const
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
virtual void set_detector_id (const short a)
virtual short get_element_id () const
virtual void set_element_id (const short a)
virtual float get_tdc_time () const
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
virtual void set_drift_distance (const float a)
virtual float get_pos () const
virtual void set_pos (const float a)
virtual bool is_in_time () const =0
virtual void set_in_time (const bool a)=0
virtual bool is_hodo_mask () const =0
virtual void set_hodo_mask (const bool a)=0
virtual bool is_trigger_mask () const =0
virtual void set_trigger_mask (const bool a)=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SHit ()
Private Member Functions
ClassDef (SHit, 1)
Detailed Description
Definition at line 17 of file SHit.h.
Member Enumeration Documentation
enum SHit::HitQuality
Enumerator
InTime
HodoMask
TriggerMask
Definition at line 63 of file SHit.h.
Constructor & Destructor Documentation
virtual SHit::~SHit () inline virtual
Definition at line 23 of file SHit.h.
SHit::SHit () inline protected
Definition at line 71 of file SHit.h.
Member Function Documentation
SHit::ClassDef (SHit , 1) private
virtual SHit* SHit::Clone () const inline virtual
Reimplemented in SHit_v1.
Definition at line 32 of file SHit.h.
Referenced by SHitMap_v1::insert(), SHitMap_v1::operator=(), and SHitMap_v1::SHitMap_v1().
virtual short SHit::get_detector_id () const inline virtual
Reimplemented in SHit_v1.
Definition at line 39 of file SHit.h.
virtual float SHit::get_drift_distance () const inline virtual
Reimplemented in SHit_v1.
Definition at line 48 of file SHit.h.
virtual short SHit::get_element_id () const inline virtual
Reimplemented in SHit_v1.
Definition at line 42 of file SHit.h.
virtual int SHit::get_hit_id () const inline virtual
Reimplemented in SHit_v1.
Definition at line 36 of file SHit.h.
Referenced by SHitMap_v1::operator=(), and SHitMap_v1::SHitMap_v1().
virtual float SHit::get_pos () const inline virtual
Reimplemented in SHit_v1.
Definition at line 51 of file SHit.h.
virtual float SHit::get_tdc_time () const inline virtual
Reimplemented in SHit_v1.
Definition at line 45 of file SHit.h.
virtual void SHit::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 27 of file SHit.h.
Referenced by ReadMySql::FillSHitMap(), and SimpleReadMySql::process_event().
virtual bool SHit::is_hodo_mask () const pure virtual
Implemented in SHit_v1.
virtual bool SHit::is_in_time () const pure virtual
Implemented in SHit_v1.
virtual bool SHit::is_trigger_mask () const pure virtual
Implemented in SHit_v1.
virtual int SHit::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 31 of file SHit.h.
virtual void SHit::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 30 of file SHit.h.
virtual void SHit::set_detector_id (const short a) inline virtual
Reimplemented in SHit_v1.
Definition at line 40 of file SHit.h.
Referenced by ReadMySql::FillSHitMap(), and SimpleReadMySql::process_event().
virtual void SHit::set_drift_distance (const float a) inline virtual
Reimplemented in SHit_v1.
Definition at line 49 of file SHit.h.
Referenced by ReadMySql::FillSHitMap(), and SimpleReadMySql::process_event().
virtual void SHit::set_element_id (const short a) inline virtual
Reimplemented in SHit_v1.
Definition at line 43 of file SHit.h.
Referenced by ReadMySql::FillSHitMap(), and SimpleReadMySql::process_event().
virtual void SHit::set_hit_id (const int a) inline virtual
Reimplemented in SHit_v1.
Definition at line 37 of file SHit.h.
Referenced by ReadMySql::FillSHitMap(), and SimpleReadMySql::process_event().
virtual void SHit::set_hodo_mask (const bool a) pure virtual
Implemented in SHit_v1.
Referenced by ReadMySql::FillSHitMap().
virtual void SHit::set_in_time (const bool a) pure virtual
Implemented in SHit_v1.
Referenced by ReadMySql::FillSHitMap().
virtual void SHit::set_pos (const float a) inline virtual
Reimplemented in SHit_v1.
Definition at line 52 of file SHit.h.
Referenced by ReadMySql::FillSHitMap().
virtual void SHit::set_tdc_time (const float a) inline virtual
Reimplemented in SHit_v1.
Definition at line 46 of file SHit.h.
Referenced by ReadMySql::FillSHitMap().
virtual void SHit::set_trigger_mask (const bool a) pure virtual
Implemented in SHit_v1.
The documentation for this class was generated from the following file:
fun4all/interfaces/SHit.h