SeaQuest Offline Software: PHOperation< T > Class Template Reference
PHOperation< T > Class Template Reference abstract
#include <fun4all/phool/PHOperation.h>
Public Member Functions
PHOperation ()
virtual ~PHOperation ()
virtual void perform (T *)=0
void operator() (T &o)
void operator() (T *o)
Detailed Description
template<class T>
class PHOperation< T >
Definition at line 9 of file PHOperation.h.
Constructor & Destructor Documentation
template<class T > PHOperation< T >::PHOperation ()
Definition at line 13 of file PHOperation.cc.
template<class T > PHOperation< T >::~PHOperation () virtual
Definition at line 17 of file PHOperation.cc.
Member Function Documentation
template<class T > void PHOperation< T >::operator() (T & o) inline
Definition at line 18 of file PHOperation.h.
References PHOperation< T >::perform().
template<class T > void PHOperation< T >::operator() (T * o) inline
Definition at line 23 of file PHOperation.h.
References PHOperation< T >::perform().
template<class T > virtual void PHOperation< T >::perform (T *) pure virtual
Referenced by PHOperation< T >::operator()().
The documentation for this class was generated from the following files:
fun4all/phool/PHOperation.h
fun4all/phool/PHOperation.cc