SeaQuest Offline Software: PHNodeReset Class Reference
PHNodeReset Class Reference
#include <fun4all/phool/PHNodeReset.h>
Public Member Functions
PHNodeReset ()
virtual ~PHNodeReset ()
Public Member Functions inherited from PHNodeOperation
PHNodeOperation ()
virtual ~PHNodeOperation ()
void operator() (PHNode &o)
void operator() (PHNode *o)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Member Functions
virtual void perform (PHNode *)
Additional Inherited Members
Protected Attributes inherited from PHNodeOperation
int verbosity
Detailed Description
Definition at line 12 of file PHNodeReset.h.
Constructor & Destructor Documentation
PHNodeReset::PHNodeReset () inline
Definition at line 15 of file PHNodeReset.h.
virtual PHNodeReset::~PHNodeReset () inline virtual
Definition at line 16 of file PHNodeReset.h.
Member Function Documentation
void PHNodeReset::perform (PHNode * node) protected virtual
Implements PHNodeOperation.
Definition at line 13 of file PHNodeReset.cc.
References PHNode::getName(), PHNode::getObjectType(), PHNode::getResetFlag(), PHNode::getType(), and True.
The documentation for this class was generated from the following files:
fun4all/phool/PHNodeReset.h
fun4all/phool/PHNodeReset.cc