SeaQuest Offline Software: SHitMap_v1 Class Reference
SHitMap_v1 Class Reference
#include <fun4all/interfaces/SHitMap_v1.h>
Public Member Functions
SHitMap_v1 ()
SHitMap_v1 (const SHitMap_v1 &hitmap)
SHitMap_v1 & operator= (const SHitMap_v1 &hitmap)
virtual ~SHitMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SHitMap * Clone () const
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SHit * get (unsigned int idkey) const
SHit * get (unsigned int idkey)
SHit * insert (const SHit *hit)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SHitMap
virtual ~SHitMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Member Functions
ClassDef (SHitMap_v1, 1)
Private Attributes
HitMap _map
Additional Inherited Members
Public Types inherited from SHitMap
typedef std::map< unsigned int,
SHit * > HitMap
typedef std::map< unsigned int,
SHit * >::const_iterator ConstIter
typedef std::map< unsigned int,
SHit * >::iterator Iter
Protected Member Functions inherited from SHitMap
SHitMap ()
Detailed Description
Definition at line 18 of file SHitMap_v1.h.
Constructor & Destructor Documentation
SHitMap_v1::SHitMap_v1 ()
Referenced by Clone().
SHitMap_v1::SHitMap_v1 (const SHitMap_v1 & hitmap)
Definition at line 23 of file SHitMap_v1.C.
References _map, begin(), SHit::Clone(), end(), and SHit::get_hit_id().
SHitMap_v1::~SHitMap_v1 () virtual
Definition at line 44 of file SHitMap_v1.C.
References Reset().
Member Function Documentation
ConstIter SHitMap_v1::begin () const inline virtual
Reimplemented from SHitMap.
Definition at line 44 of file SHitMap_v1.h.
References _map.
Referenced by operator=(), and SHitMap_v1().
Iter SHitMap_v1::begin () inline virtual
Reimplemented from SHitMap.
Definition at line 48 of file SHitMap_v1.h.
References _map.
SHitMap_v1::ClassDef (SHitMap_v1 , 1) private
void SHitMap_v1::clear () inline virtual
Reimplemented from SHitMap.
Definition at line 35 of file SHitMap_v1.h.
References Reset().
SHitMap* SHitMap_v1::Clone () const inline virtual
Reimplemented from SHitMap.
Definition at line 30 of file SHitMap_v1.h.
References SHitMap_v1().
size_t SHitMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SHitMap.
Definition at line 34 of file SHitMap_v1.h.
References _map.
bool SHitMap_v1::empty () const inline virtual
Reimplemented from SHitMap.
Definition at line 32 of file SHitMap_v1.h.
References _map.
ConstIter SHitMap_v1::end () const inline virtual
Reimplemented from SHitMap.
Definition at line 46 of file SHitMap_v1.h.
References _map.
Referenced by operator=(), and SHitMap_v1().
Iter SHitMap_v1::end () inline virtual
Reimplemented from SHitMap.
Definition at line 50 of file SHitMap_v1.h.
References _map.
size_t SHitMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SHitMap.
Definition at line 40 of file SHitMap_v1.h.
References _map.
ConstIter SHitMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SHitMap.
Definition at line 45 of file SHitMap_v1.h.
References _map.
Iter SHitMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SHitMap.
Definition at line 49 of file SHitMap_v1.h.
References _map.
const SHit * SHitMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SHitMap.
Definition at line 63 of file SHitMap_v1.C.
References _map.
SHit * SHitMap_v1::get (unsigned int idkey) virtual
Reimplemented from SHitMap.
Definition at line 69 of file SHitMap_v1.C.
References _map.
void SHitMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SHitMap.
Definition at line 58 of file SHitMap_v1.C.
References _map.
SHit * SHitMap_v1::insert (const SHit * hit) virtual
Reimplemented from SHitMap.
Definition at line 75 of file SHitMap_v1.C.
References _map, and SHit::Clone().
int SHitMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SHitMap.
Definition at line 29 of file SHitMap_v1.h.
SHitMap_v1 & SHitMap_v1::operator= (const SHitMap_v1 & hitmap)
Definition at line 33 of file SHitMap_v1.C.
References _map, begin(), SHit::Clone(), end(), SHit::get_hit_id(), and Reset().
void SHitMap_v1::Reset () virtual
Clear Event.
Reimplemented from SHitMap.
Definition at line 48 of file SHitMap_v1.C.
References _map.
Referenced by clear(), operator=(), and ~SHitMap_v1().
size_t SHitMap_v1::size () const inline virtual
Reimplemented from SHitMap.
Definition at line 33 of file SHitMap_v1.h.
References _map.
Member Data Documentation
HitMap SHitMap_v1::_map private
Definition at line 53 of file SHitMap_v1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), SHitMap_v1(), and size().
The documentation for this class was generated from the following files:
fun4all/interfaces/SHitMap_v1.h
fun4all/interfaces/SHitMap_v1.C