SeaQuest Offline Software: Fun4AllOutputManager Class Reference
Fun4AllOutputManager Class Reference
#include <fun4all/fun4all/Fun4AllOutputManager.h>
Public Member Functions
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int Write (PHCompositeNode *)
write starting from given node
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector
< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 11 of file Fun4AllOutputManager.h.
Constructor & Destructor Documentation
virtual Fun4AllOutputManager::~Fun4AllOutputManager () inline virtual
destructor
Definition at line 16 of file Fun4AllOutputManager.h.
Fun4AllOutputManager::Fun4AllOutputManager (const std::string & myname) protected
constructor. is protected since we do not want the class to be created in root macros
Definition at line 10 of file Fun4AllOutputManager.cc.
References nEvents.
Member Function Documentation
int Fun4AllOutputManager::AddEventSelector (const std::string & recomodule) virtual
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
Definition at line 18 of file Fun4AllOutputManager.cc.
References EventSelectors.
virtual int Fun4AllOutputManager::AddNode (const std::string &) inline virtual
add a node in outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 23 of file Fun4AllOutputManager.h.
int Fun4AllOutputManager::DoNotWriteEvent (std::vector< int > * retcodes) const virtual
decides if event is to be written or not
Definition at line 67 of file Fun4AllOutputManager.cc.
References recomoduleindex.
virtual std::vector<std::string>* Fun4AllOutputManager::EventSelector () inline virtual
retrieves pointer to vector of event selector module names
Definition at line 57 of file Fun4AllOutputManager.h.
References EventSelectors.
Referenced by Fun4AllServer::UpdateEventSelector().
virtual size_t Fun4AllOutputManager::EventsWritten () const inline virtual
get number of Events
Definition at line 68 of file Fun4AllOutputManager.h.
References nEvents.
Referenced by Print().
virtual std::string Fun4AllOutputManager::OutFileName () const inline virtual
get output file name
Definition at line 71 of file Fun4AllOutputManager.h.
References outfilename.
virtual int Fun4AllOutputManager::outfileopen (const std::string &) inline virtual
opens output file
Reimplemented in Fun4AllPrdfOutputManager, Fun4AllEventOutputManager, and Fun4AllDstOutputManager.
Definition at line 38 of file Fun4AllOutputManager.h.
void Fun4AllOutputManager::Print (const std::string & what = "ALL") const virtual
print method (dump event selector)
Reimplemented from Fun4AllBase.
Reimplemented in Fun4AllEventOutputManager, and Fun4AllDstOutputManager.
Definition at line 46 of file Fun4AllOutputManager.cc.
References EventSelectors, EventsWritten(), recomoduleindex, and Fun4AllBase::ThisName.
Referenced by Fun4AllDstOutputManager::Print(), Fun4AllEventOutputManager::Print(), and Fun4AllServer::Print().
virtual std::vector<unsigned>* Fun4AllOutputManager::RecoModuleIndex () inline virtual
retrieves pointer to vector of event selector module ids
Definition at line 61 of file Fun4AllOutputManager.h.
References recomoduleindex.
Referenced by Fun4AllServer::UpdateEventSelector().
virtual int Fun4AllOutputManager::RemoveNode (const std::string &) inline virtual
removes a node from outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 42 of file Fun4AllOutputManager.h.
virtual int Fun4AllOutputManager::StripNode (const std::string &) inline virtual
not write a node in outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 27 of file Fun4AllOutputManager.h.
virtual int Fun4AllOutputManager::Write (PHCompositeNode *) inline virtual
write starting from given node
Reimplemented in Fun4AllEventOutputManager, Fun4AllPrdfOutputManager, and Fun4AllDstOutputManager.
Definition at line 49 of file Fun4AllOutputManager.h.
Referenced by WriteGeneric().
int Fun4AllOutputManager::WriteGeneric (PHCompositeNode * startNode)
Common method, called before calling virtual Write.
Definition at line 37 of file Fun4AllOutputManager.cc.
References nEvents, and Write().
virtual int Fun4AllOutputManager::WriteNode (PHCompositeNode *) inline virtual
write specified node
Reimplemented in Fun4AllDstOutputManager.
Definition at line 53 of file Fun4AllOutputManager.h.
Member Data Documentation
std::vector<std::string> Fun4AllOutputManager::EventSelectors protected
vector of event selectors modules
Definition at line 85 of file Fun4AllOutputManager.h.
Referenced by AddEventSelector(), EventSelector(), and Print().
size_t Fun4AllOutputManager::nEvents protected
Number of Events.
Definition at line 82 of file Fun4AllOutputManager.h.
Referenced by EventsWritten(), Fun4AllOutputManager(), and WriteGeneric().
std::string Fun4AllOutputManager::outfilename protected
output file name
Definition at line 91 of file Fun4AllOutputManager.h.
Referenced by Fun4AllDstOutputManager::Fun4AllDstOutputManager(), Fun4AllPrdfOutputManager::Fun4AllPrdfOutputManager(), Fun4AllPrdfOutputManager::InitPrdfManager(), OutFileName(), Fun4AllPrdfOutputManager::outfileopen(), Fun4AllDstOutputManager::Print(), Fun4AllEventOutputManager::SetOutfileName(), and Fun4AllDstOutputManager::WriteNode().
std::vector<unsigned> Fun4AllOutputManager::recomoduleindex protected
vector of associated module indexes
Definition at line 88 of file Fun4AllOutputManager.h.
Referenced by DoNotWriteEvent(), Print(), and RecoModuleIndex().
The documentation for this class was generated from the following files:
fun4all/fun4all/Fun4AllOutputManager.h
fun4all/fun4all/Fun4AllOutputManager.cc