SeaQuest Offline Software: SimpleReadMySql Class Reference
SimpleReadMySql Class Reference
#include <fun4all/modules/SimpleReadMySql.h>
Public Member Functions
SimpleReadMySql (const std::string &name="SimpleReadMySql")
virtual ~SimpleReadMySql ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int MakeNodes (PHCompositeNode *topNode)
int GetNodes (PHCompositeNode *topNode)
int makeQueryInput ()
bool nextEntry ()
int getInt (int id, int default_val=0)
float getFloat (int id, float default_val=0.)
double getDouble (int id, double default_val=0.)
std::string getString (int id, std::string default_val="")
Private Attributes
std::string _server_name
int _port
std::string _user_name
std::string _password
std::string _input_shcema
std::string _table_name
int _run_id
int _spill_id
char query [2000]
TSQLServer * inputServer
TSQLResult * res
TSQLRow * row
std::vector< int > eventIDs
size_t _event
SHitMap * _hit_map
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 33 of file SimpleReadMySql.h.
Constructor & Destructor Documentation
SimpleReadMySql::SimpleReadMySql (const std::string & name = "SimpleReadMySql")
Definition at line 35 of file SimpleReadMySql.C.
References eventIDs.
virtual SimpleReadMySql::~SimpleReadMySql () inline virtual
Definition at line 38 of file SimpleReadMySql.h.
Member Function Documentation
int SimpleReadMySql::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 129 of file SimpleReadMySql.C.
References Fun4AllReturnCodes::EVENT_OK.
double SimpleReadMySql::getDouble (int id, double default_val = 0.) private
Definition at line 214 of file SimpleReadMySql.C.
References row.
float SimpleReadMySql::getFloat (int id, float default_val = 0.) private
Definition at line 204 of file SimpleReadMySql.C.
References row.
Referenced by process_event().
int SimpleReadMySql::getInt (int id, int default_val = 0) private
Definition at line 187 of file SimpleReadMySql.C.
References row.
Referenced by InitRun(), and process_event().
int SimpleReadMySql::GetNodes (PHCompositeNode * topNode) private
Definition at line 153 of file SimpleReadMySql.C.
References _hit_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogError.
Referenced by process_event().
std::string SimpleReadMySql::getString (int id, std::string default_val = "") private
Definition at line 224 of file SimpleReadMySql.C.
References row.
int SimpleReadMySql::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 54 of file SimpleReadMySql.C.
References Fun4AllReturnCodes::EVENT_OK.
int SimpleReadMySql::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 58 of file SimpleReadMySql.C.
References _input_shcema, _password, _port, _server_name, _user_name, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, eventIDs, getInt(), inputServer, LogDebug, LogError, MakeNodes(), makeQueryInput(), nextEntry(), query, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_QUIET.
int SimpleReadMySql::MakeNodes (PHCompositeNode * topNode) private
Definition at line 133 of file SimpleReadMySql.C.
References _hit_map, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), LogInfo, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
Referenced by InitRun().
int SimpleReadMySql::makeQueryInput () private
Definition at line 164 of file SimpleReadMySql.C.
References inputServer, query, and res.
Referenced by InitRun(), and process_event().
bool SimpleReadMySql::nextEntry () private
Definition at line 176 of file SimpleReadMySql.C.
References res, and row.
Referenced by InitRun(), and process_event().
int SimpleReadMySql::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 94 of file SimpleReadMySql.C.
References _event, _hit_map, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, eventIDs, getFloat(), getInt(), GetNodes(), SHit::identify(), SHitMap::insert(), makeQueryInput(), nextEntry(), query, SHit::set_detector_id(), SHit::set_drift_distance(), SHit::set_element_id(), SHit::set_hit_id(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Member Data Documentation
size_t SimpleReadMySql::_event private
Definition at line 78 of file SimpleReadMySql.h.
Referenced by process_event().
SHitMap* SimpleReadMySql::_hit_map private
Definition at line 80 of file SimpleReadMySql.h.
Referenced by GetNodes(), MakeNodes(), and process_event().
std::string SimpleReadMySql::_input_shcema private
Definition at line 64 of file SimpleReadMySql.h.
Referenced by InitRun().
std::string SimpleReadMySql::_password private
Definition at line 63 of file SimpleReadMySql.h.
Referenced by InitRun().
int SimpleReadMySql::_port private
Definition at line 61 of file SimpleReadMySql.h.
Referenced by InitRun().
int SimpleReadMySql::_run_id private
Definition at line 66 of file SimpleReadMySql.h.
std::string SimpleReadMySql::_server_name private
Definition at line 60 of file SimpleReadMySql.h.
Referenced by InitRun().
int SimpleReadMySql::_spill_id private
Definition at line 67 of file SimpleReadMySql.h.
std::string SimpleReadMySql::_table_name private
Definition at line 65 of file SimpleReadMySql.h.
std::string SimpleReadMySql::_user_name private
Definition at line 62 of file SimpleReadMySql.h.
Referenced by InitRun().
std::vector<int> SimpleReadMySql::eventIDs private
Definition at line 77 of file SimpleReadMySql.h.
Referenced by InitRun(), process_event(), and SimpleReadMySql().
TSQLServer* SimpleReadMySql::inputServer private
Definition at line 73 of file SimpleReadMySql.h.
Referenced by InitRun(), and makeQueryInput().
char SimpleReadMySql::query[2000] private
Definition at line 70 of file SimpleReadMySql.h.
Referenced by InitRun(), makeQueryInput(), and process_event().
TSQLResult* SimpleReadMySql::res private
Definition at line 74 of file SimpleReadMySql.h.
Referenced by makeQueryInput(), and nextEntry().
TSQLRow* SimpleReadMySql::row private
Definition at line 75 of file SimpleReadMySql.h.
Referenced by getDouble(), getFloat(), getInt(), getString(), and nextEntry().
The documentation for this class was generated from the following files:
fun4all/modules/SimpleReadMySql.h
fun4all/modules/SimpleReadMySql.C