SeaQuest Offline Software: Fun4AllPrdfOutputManager Class Reference
Fun4AllPrdfOutputManager Class Reference
#include <fun4all/fun4all/Fun4AllPrdfOutputManager.h>
Public Member Functions
Fun4AllPrdfOutputManager (const std::string &myname="PRDFOUT", const std::string &filename="data_out.prdf")
constructor
virtual ~Fun4AllPrdfOutputManager (void)
destructor
int InitPrdfNode (PHCompositeNode *top_node, const std::string &nodeName="SIMPRDF")
PRDF node initialization [class specific method].
int outfileopen (const std::string &fname)
reinitialize raw output manager to write to new filename. Close old one if any
int Write (PHCompositeNode *startNode)
event write method (startNode argument is ignored. prdfNode is always used)
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector
< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int InitPrdfManager (void)
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
PHCompositeNode * prdfNode
prdf node
PHRawOManager * prdfOut
output manager
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 10 of file Fun4AllPrdfOutputManager.h.
Constructor & Destructor Documentation
Fun4AllPrdfOutputManager::Fun4AllPrdfOutputManager (const std::string & myname = "PRDFOUT", const std::string & filename = "data_out.prdf")
constructor
Definition at line 15 of file Fun4AllPrdfOutputManager.cc.
References Fun4AllOutputManager::outfilename.
Fun4AllPrdfOutputManager::~Fun4AllPrdfOutputManager (void) virtual
destructor
Definition at line 25 of file Fun4AllPrdfOutputManager.cc.
References prdfOut.
Member Function Documentation
int Fun4AllPrdfOutputManager::InitPrdfManager (void) protected
initialize prdf output manager every time the output file name is changed including first event
Definition at line 93 of file Fun4AllPrdfOutputManager.cc.
References PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), Fun4AllOutputManager::outfilename, and prdfOut.
Referenced by Write().
int Fun4AllPrdfOutputManager::InitPrdfNode (PHCompositeNode * top_node, const std::string & nodeName = "SIMPRDF")
PRDF node initialization [class specific method].
Definition at line 32 of file Fun4AllPrdfOutputManager.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and prdfNode.
int Fun4AllPrdfOutputManager::outfileopen (const std::string & fname) virtual
reinitialize raw output manager to write to new filename. Close old one if any
Reimplemented from Fun4AllOutputManager.
Definition at line 54 of file Fun4AllPrdfOutputManager.cc.
References Fun4AllOutputManager::outfilename, prdfOut, and Fun4AllBase::verbosity.
int Fun4AllPrdfOutputManager::Write (PHCompositeNode * startNode) virtual
event write method (startNode argument is ignored. prdfNode is always used)
Reimplemented from Fun4AllOutputManager.
Definition at line 70 of file Fun4AllPrdfOutputManager.cc.
References InitPrdfManager(), prdfNode, and prdfOut.
Member Data Documentation
PHCompositeNode* Fun4AllPrdfOutputManager::prdfNode protected
prdf node
Definition at line 38 of file Fun4AllPrdfOutputManager.h.
Referenced by InitPrdfNode(), and Write().
PHRawOManager* Fun4AllPrdfOutputManager::prdfOut protected
output manager
Definition at line 41 of file Fun4AllPrdfOutputManager.h.
Referenced by InitPrdfManager(), outfileopen(), Write(), and ~Fun4AllPrdfOutputManager().
The documentation for this class was generated from the following files:
fun4all/fun4all/Fun4AllPrdfOutputManager.h
fun4all/fun4all/Fun4AllPrdfOutputManager.cc