SeaQuest Offline Software: PHPointerList< T > Class Template Reference
PHPointerList< T > Class Template Reference
#include <fun4all/phool/PHPointerList.h>
Public Member Functions
PHPointerList (size_t=2)
PHPointerList (const PHPointerList< T > &)
PHPointerList< T > & operator= (const PHPointerList< T > &)
virtual ~PHPointerList ()
T * operator[] (size_t) const
void clear ()
void clearAndDestroy ()
size_t length () const
T * removeLast ()
T * removeAt (size_t)
PHBoolean append (T *)
PHBoolean insertAt (T *, size_t)
Private Member Functions
PHBoolean grow (size_t=0)
Private Attributes
T ** items
size_t maxNItems
size_t nItems
Detailed Description
template<class T>
class PHPointerList< T >
Definition at line 33 of file PHPointerList.h.
Constructor & Destructor Documentation
template<class T > PHPointerList< T >::PHPointerList (size_t initialSize = 2)
Definition at line 63 of file PHPointerList.h.
template<class T> PHPointerList< T >::PHPointerList (const PHPointerList< T > & l)
Definition at line 71 of file PHPointerList.h.
template<class T > PHPointerList< T >::~PHPointerList () virtual
Definition at line 93 of file PHPointerList.h.
Member Function Documentation
template<class T> PHBoolean PHPointerList< T >::append (T * item) inline
Definition at line 142 of file PHPointerList.h.
References False, and True.
Referenced by PHCompositeNode::addNode(), and PHNodeIterator::ls().
template<class T > void PHPointerList< T >::clear () inline
Definition at line 193 of file PHPointerList.h.
Referenced by PHNodeIterator::ls().
template<class T > void PHPointerList< T >::clearAndDestroy () inline
Definition at line 201 of file PHPointerList.h.
Referenced by PHCompositeNode::~PHCompositeNode().
template<class T > PHBoolean PHPointerList< T >::grow (size_t newSize = 0) private
Definition at line 101 of file PHPointerList.h.
References False, and True.
template<class T> PHBoolean PHPointerList< T >::insertAt (T * item, size_t pos) inline
Definition at line 168 of file PHPointerList.h.
References False, and True.
template<class T > size_t PHPointerList< T >::length () const inline
Definition at line 213 of file PHPointerList.h.
Referenced by PHPointerList< T >::operator=().
template<class T> PHPointerList< T > & PHPointerList< T >::operator= (const PHPointerList< T > & l)
Definition at line 78 of file PHPointerList.h.
References PHPointerList< T >::length(), and PHPointerList< T >::maxNItems.
template<class T > T * PHPointerList< T >::operator[] (size_t i) const inline
Definition at line 127 of file PHPointerList.h.
template<class T > T * PHPointerList< T >::removeAt (size_t i) inline
Definition at line 235 of file PHPointerList.h.
Referenced by PHCompositeNode::forgetMe(), and PHCompositeNode::prune().
template<class T > T * PHPointerList< T >::removeLast () inline
Definition at line 220 of file PHPointerList.h.
Member Data Documentation
template<class T> T** PHPointerList< T >::items private
Definition at line 56 of file PHPointerList.h.
template<class T> size_t PHPointerList< T >::maxNItems private
Definition at line 57 of file PHPointerList.h.
Referenced by PHPointerList< T >::operator=().
template<class T> size_t PHPointerList< T >::nItems private
Definition at line 58 of file PHPointerList.h.
The documentation for this class was generated from the following file:
fun4all/phool/PHPointerList.h