SeaQuest Offline Software: Fun4AllPrdfInputManager Class Reference
Fun4AllPrdfInputManager Class Reference
#include <fun4all/fun4all/Fun4AllPrdfInputManager.h>
Public Member Functions
Fun4AllPrdfInputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllPrdfInputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
int isOpen ()
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenNextFile ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int segment
int isopen
int events_total
int events_thisfile
std::string topNodeName
PHCompositeNode * topNode
Event * evt
Event * save_evt
Eventiterator * eventiterator
SyncObject * syncobject
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 14 of file Fun4AllPrdfInputManager.h.
Constructor & Destructor Documentation
Fun4AllPrdfInputManager::Fun4AllPrdfInputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 28 of file Fun4AllPrdfInputManager.cc.
References PHCompositeNode::addNode(), evt, PHNodeIterator::findFirst(), Fun4AllServer::instance(), syncobject, topNode, Fun4AllServer::topNode(), and topNodeName.
Fun4AllPrdfInputManager::~Fun4AllPrdfInputManager () virtual
Definition at line 52 of file Fun4AllPrdfInputManager.cc.
References fileclose(), isopen, and syncobject.
Member Function Documentation
int Fun4AllPrdfInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 164 of file Fun4AllPrdfInputManager.cc.
References eventiterator, Fun4AllInputManager::filelist, isopen, Fun4AllBase::Name(), and Fun4AllInputManager::repeat.
Referenced by fileopen(), PushBackEvents(), run(), and ~Fun4AllPrdfInputManager().
int Fun4AllPrdfInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 61 of file Fun4AllPrdfInputManager.cc.
References Fun4AllInputManager::AddToFileOpened(), eventiterator, events_thisfile, fileclose(), Fun4AllInputManager::filename, Fun4AllUtils::GetRunSegment(), isopen, PHWHERE, segment, Fun4AllBase::ThisName, and Fun4AllBase::verbosity.
Referenced by OpenNextFile().
int Fun4AllPrdfInputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 291 of file Fun4AllPrdfInputManager.cc.
References SyncObject::clone(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
int Fun4AllPrdfInputManager::isOpen () inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 22 of file Fun4AllPrdfInputManager.h.
References isopen.
int Fun4AllPrdfInputManager::OpenNextFile () protected
Definition at line 201 of file Fun4AllPrdfInputManager.cc.
References Fun4AllInputManager::filelist, fileopen(), PHWHERE, and Fun4AllBase::verbosity.
Referenced by run().
void Fun4AllPrdfInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 194 of file Fun4AllPrdfInputManager.cc.
References Fun4AllInputManager::Print().
int Fun4AllPrdfInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 237 of file Fun4AllPrdfInputManager.cc.
References eventiterator, evt, fileclose(), PHWHERE, save_evt, Fun4AllBase::ThisName, and Fun4AllBase::verbosity.
int Fun4AllPrdfInputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 225 of file Fun4AllPrdfInputManager.cc.
References evt, PHNodeIterator::findFirst(), SyncObject::Reset(), PHDataNode< T >::setData(), syncobject, and topNode.
Referenced by run().
int Fun4AllPrdfInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 94 of file Fun4AllPrdfInputManager.cc.
References Fun4AllSyncManager::CurrentEvent(), Fun4AllReturnCodes::EVENT_OK, SyncObject::EventCounter(), eventiterator, SyncObject::EventNumber(), events_thisfile, events_total, evt, fileclose(), Fun4AllInputManager::filelist, PHNodeIterator::findFirst(), isopen, Fun4AllInputManager::mySyncManager, Fun4AllBase::Name(), OpenNextFile(), Fun4AllSyncManager::PrdfEvents(), Fun4AllInputManager::RejectEvent(), ResetEvent(), SyncObject::RunNumber(), save_evt, segment, Fun4AllSyncManager::SegmentNumber(), SyncObject::SegmentNumber(), PHDataNode< T >::setData(), Fun4AllInputManager::SetRunNumber(), syncobject, Fun4AllBase::ThisName, topNode, and Fun4AllBase::verbosity.
int Fun4AllPrdfInputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 309 of file Fun4AllPrdfInputManager.cc.
References SyncObject::Different(), Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, and syncobject.
Member Data Documentation
Eventiterator* Fun4AllPrdfInputManager::eventiterator protected
Definition at line 40 of file Fun4AllPrdfInputManager.h.
Referenced by fileclose(), fileopen(), PushBackEvents(), and run().
int Fun4AllPrdfInputManager::events_thisfile protected
Definition at line 35 of file Fun4AllPrdfInputManager.h.
Referenced by fileopen(), and run().
int Fun4AllPrdfInputManager::events_total protected
Definition at line 34 of file Fun4AllPrdfInputManager.h.
Referenced by run().
Event* Fun4AllPrdfInputManager::evt protected
Definition at line 38 of file Fun4AllPrdfInputManager.h.
Referenced by Fun4AllPrdfInputManager(), PushBackEvents(), ResetEvent(), and run().
int Fun4AllPrdfInputManager::isopen protected
Definition at line 33 of file Fun4AllPrdfInputManager.h.
Referenced by fileclose(), fileopen(), isOpen(), run(), and ~Fun4AllPrdfInputManager().
Event* Fun4AllPrdfInputManager::save_evt protected
Definition at line 39 of file Fun4AllPrdfInputManager.h.
Referenced by PushBackEvents(), and run().
int Fun4AllPrdfInputManager::segment protected
Definition at line 32 of file Fun4AllPrdfInputManager.h.
Referenced by fileopen(), and run().
SyncObject* Fun4AllPrdfInputManager::syncobject protected
Definition at line 41 of file Fun4AllPrdfInputManager.h.
Referenced by Fun4AllPrdfInputManager(), GetSyncObject(), ResetEvent(), run(), SyncIt(), and ~Fun4AllPrdfInputManager().
PHCompositeNode* Fun4AllPrdfInputManager::topNode protected
Definition at line 37 of file Fun4AllPrdfInputManager.h.
Referenced by Fun4AllPrdfInputManager(), ResetEvent(), and run().
std::string Fun4AllPrdfInputManager::topNodeName protected
Definition at line 36 of file Fun4AllPrdfInputManager.h.
Referenced by Fun4AllPrdfInputManager().
The documentation for this class was generated from the following files:
fun4all/fun4all/Fun4AllPrdfInputManager.h
fun4all/fun4all/Fun4AllPrdfInputManager.cc