SeaQuest Offline Software: SEvent Class Reference
SEvent Class Reference abstract
#include <fun4all/interfaces/SEvent.h>
Public Types
enum TriggerMask {
NIM1 = 0, NIM2 = 1, NIM3 = 2, NIM4 = 3,
NIM5 = 4, MATRIX1 = 5, MATRIX2 = 6, MATRIX3 = 7,
MATRIX4 = 8, MATRIX5 = 9
}
Public Member Functions
virtual ~SEvent ()
void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int get_run_id () const =0
virtual void set_run_id (const int a)=0
virtual int get_spill_id () const =0
virtual void set_spill_id (const int a)=0
virtual int get_event_id () const =0
virtual void set_event_id (const int a)=0
virtual int get_coda_event_id () const =0
virtual void set_coda_event_id (const int a)=0
virtual int get_data_quality () const =0
virtual void set_data_quality (const int a)=0
virtual int get_vme_time () const =0
virtual void set_vme_time (const int a)=0
virtual bool get_trigger (const SEvent::TriggerMask i) const =0
virtual void set_trigger (const SEvent::TriggerMask i, const bool a)=0
virtual int get_raw_matrix (const unsigned short i) const =0
virtual void set_raw_matrix (const unsigned short i, const bool a)=0
virtual int get_after_inh_matrix (const unsigned short i) const =0
virtual void set_after_inh_matrix (const unsigned short i, const bool a)=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SEvent ()
ClassDef (SEvent, 1)
Detailed Description
Definition at line 18 of file SEvent.h.
Member Enumeration Documentation
enum SEvent::TriggerMask
Enumerator
NIM1
NIM2
NIM3
NIM4
NIM5
MATRIX1
MATRIX2
MATRIX3
MATRIX4
MATRIX5
Definition at line 22 of file SEvent.h.
Constructor & Destructor Documentation
virtual SEvent::~SEvent () inline virtual
Definition at line 35 of file SEvent.h.
SEvent::SEvent () inline protected
Definition at line 77 of file SEvent.h.
Member Function Documentation
SEvent::ClassDef (SEvent , 1) protected
virtual int SEvent::get_after_inh_matrix (const unsigned short i) const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_coda_event_id () const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_data_quality () const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_event_id () const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_raw_matrix (const unsigned short i) const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_run_id () const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_spill_id () const pure virtual
Implemented in SEvent_v1.
virtual bool SEvent::get_trigger (const SEvent::TriggerMask i) const pure virtual
Implemented in SEvent_v1.
virtual int SEvent::get_vme_time () const pure virtual
Implemented in SEvent_v1.
virtual void SEvent::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SEvent_v1.
Definition at line 39 of file SEvent.h.
void SEvent::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SEvent_v1.
Definition at line 37 of file SEvent.h.
virtual void SEvent::set_after_inh_matrix (const unsigned short i, const bool a) pure virtual
Implemented in SEvent_v1.
virtual void SEvent::set_coda_event_id (const int a) pure virtual
Implemented in SEvent_v1.
Referenced by ReadMySql::FillSEvent().
virtual void SEvent::set_data_quality (const int a) pure virtual
Implemented in SEvent_v1.
virtual void SEvent::set_event_id (const int a) pure virtual
Implemented in SEvent_v1.
Referenced by ReadMySql::FillSEvent().
virtual void SEvent::set_raw_matrix (const unsigned short i, const bool a) pure virtual
Implemented in SEvent_v1.
virtual void SEvent::set_run_id (const int a) pure virtual
Implemented in SEvent_v1.
Referenced by ReadMySql::FillSEvent().
virtual void SEvent::set_spill_id (const int a) pure virtual
Implemented in SEvent_v1.
Referenced by ReadMySql::FillSEvent().
virtual void SEvent::set_trigger (const SEvent::TriggerMask i, const bool a) pure virtual
Implemented in SEvent_v1.
Referenced by ReadMySql::FillSEvent().
virtual void SEvent::set_vme_time (const int a) pure virtual
Implemented in SEvent_v1.
The documentation for this class was generated from the following file:
fun4all/interfaces/SEvent.h