SeaQuest Offline Software: PHTimer::Frequency Class Reference
PHTimer::Frequency Class Reference
internal frequency read from cpu information file
Public Member Functions
Frequency ()
constructor
operator double () const
frequency accessor
double period () const
period accessor
Private Member Functions
void set_cpu_freq (const char *cpuinfopath="/proc/cpuinfo")
read pc frequency from cpuinfo place
Private Attributes
double _frequency
pc frequency
double _period
pc period
Detailed Description
internal frequency read from cpu information file
Definition at line 131 of file PHTimer.h.
Constructor & Destructor Documentation
PHTimer::Frequency::Frequency () inline
constructor
Definition at line 136 of file PHTimer.h.
References _frequency, _period, and set_cpu_freq().
Member Function Documentation
PHTimer::Frequency::operator double () const inline
frequency accessor
Definition at line 144 of file PHTimer.h.
References _frequency.
double PHTimer::Frequency::period () const inline
period accessor
Definition at line 148 of file PHTimer.h.
References _period.
Referenced by PHTimer::get_difference().
void PHTimer::Frequency::set_cpu_freq (const char * cpuinfopath = "/proc/cpuinfo") private
read pc frequency from cpuinfo place
Definition at line 24 of file PHTimer.cc.
References _frequency.
Referenced by Frequency().
Member Data Documentation
double PHTimer::Frequency::_frequency private
pc frequency
Definition at line 154 of file PHTimer.h.
Referenced by Frequency(), operator double(), and set_cpu_freq().
double PHTimer::Frequency::_period private
pc period
Definition at line 157 of file PHTimer.h.
Referenced by Frequency(), and period().
The documentation for this class was generated from the following files:
fun4all/phool/PHTimer.h
fun4all/phool/PHTimer.cc